### ISSUE TITLE
No comment links added on page

### ISSUE THREAD

**Issue by Ajnasz** [Ajnasz/hupper#23]
http://hup.hu/node/152356?comments_per_page=9999

JS error in chrome:
Error in event handler for (unknown): TypeError: Cannot read property 'querySelector' of null
    at addFooterLink (chrome-extension://nlfhdcgbalmfboijgcfenidpdgbchflo/data/bundle.js:1265:33)
    at addParentLinkToComment (chrome-extension://nlfhdcgbalmfboijgcfenidpdgbchflo/data/bundle.js:1293:3)
    at Object.addParentLinkToComments (chrome-extension://nlfhdcgbalmfboijgcfenidpdgbchflo/data/bundle.js:1307:12)
    at chrome-extension://nlfhdcgbalmfboijgcfenidpdgbchflo/data/bundle.js:1984:16

**Comment by Ajnasz** [comment]
Issue is with `comment-2072525`, bad markup caused that no footer found in the comment

**Comment by Ajnasz** [comment]
Fixed in version 2.1.7
